# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: devices.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rdevices.proto\"\x1f\n\rClientCommand\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\"<\n\nDeviceInfo\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\"*\n\nDeviceList\x12\x1c\n\x07\x64\x65vices\x18\x01 \x03(\x0b\x32\x0b.DeviceInfo\".\n\x0fTemperatureData\x12\x1b\n\x13\x63urrent_temperature\x18\x01 \x01(\x01\"3\n\x12TemperatureCommand\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\"$\n\x05\x43\x61\x62le\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\"$\n\tStreaming\x12\x0b\n\x03\x61pp\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\"A\n\tTVOptions\x12\x15\n\x05\x43\x61\x62le\x18\x01 \x03(\x0b\x32\x06.Cable\x12\x1d\n\tstreaming\x18\x02 \x03(\x0b\x32\n.Streaming\"*\n\tTVCommand\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\" \n\x08TimeData\x12\x14\n\x0c\x63urrent_time\x18\x01 \x01(\t\"e\n\x0bLampCommand\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x12\n\nlamp_state\x18\x02 \x01(\t\x12\x18\n\x10upper_limit_lamp\x18\x03 \x01(\t\x12\x18\n\x10lower_limit_lamp\x18\x04 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'devices_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLIENTCOMMAND._serialized_start=17
  _CLIENTCOMMAND._serialized_end=48
  _DEVICEINFO._serialized_start=50
  _DEVICEINFO._serialized_end=110
  _DEVICELIST._serialized_start=112
  _DEVICELIST._serialized_end=154
  _TEMPERATUREDATA._serialized_start=156
  _TEMPERATUREDATA._serialized_end=202
  _TEMPERATURECOMMAND._serialized_start=204
  _TEMPERATURECOMMAND._serialized_end=255
  _CABLE._serialized_start=257
  _CABLE._serialized_end=293
  _STREAMING._serialized_start=295
  _STREAMING._serialized_end=331
  _TVOPTIONS._serialized_start=333
  _TVOPTIONS._serialized_end=398
  _TVCOMMAND._serialized_start=400
  _TVCOMMAND._serialized_end=442
  _TIMEDATA._serialized_start=444
  _TIMEDATA._serialized_end=476
  _LAMPCOMMAND._serialized_start=478
  _LAMPCOMMAND._serialized_end=579
# @@protoc_insertion_point(module_scope)
