# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: devices.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='devices.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rdevices.proto\"6\n\rClientCommand\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x15\n\rtarget_device\x18\x02 \x01(\t\"<\n\nDeviceInfo\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\"*\n\nDeviceList\x12\x1c\n\x07\x64\x65vices\x18\x01 \x03(\x0b\x32\x0b.DeviceInfo\"A\n\x0fTemperatureData\x12\x1b\n\x13\x63urrent_temperature\x18\x01 \x01(\x01\x12\x11\n\tdevice_id\x18\x02 \x01(\t\"3\n\x12TemperatureCommand\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\"$\n\x05\x43\x61\x62le\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\"$\n\tStreaming\x12\x0b\n\x03\x61pp\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\"A\n\tTVOptions\x12\x15\n\x05\x43\x61\x62le\x18\x01 \x03(\x0b\x32\x06.Cable\x12\x1d\n\tstreaming\x18\x02 \x03(\x0b\x32\n.Streaming\"*\n\tTVCommand\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\" \n\x08TimeData\x12\x14\n\x0c\x63urrent_time\x18\x01 \x01(\t\"e\n\x0bLampCommand\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x12\n\nlamp_state\x18\x02 \x01(\t\x12\x18\n\x10upper_limit_lamp\x18\x03 \x01(\t\x12\x18\n\x10lower_limit_lamp\x18\x04 \x01(\tb\x06proto3'
)




_CLIENTCOMMAND = _descriptor.Descriptor(
  name='ClientCommand',
  full_name='ClientCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='ClientCommand.action', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='target_device', full_name='ClientCommand.target_device', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=71,
)


_DEVICEINFO = _descriptor.Descriptor(
  name='DeviceInfo',
  full_name='DeviceInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_id', full_name='DeviceInfo.device_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='DeviceInfo.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='DeviceInfo.state', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=133,
)


_DEVICELIST = _descriptor.Descriptor(
  name='DeviceList',
  full_name='DeviceList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='devices', full_name='DeviceList.devices', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=177,
)


_TEMPERATUREDATA = _descriptor.Descriptor(
  name='TemperatureData',
  full_name='TemperatureData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='current_temperature', full_name='TemperatureData.current_temperature', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device_id', full_name='TemperatureData.device_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=244,
)


_TEMPERATURECOMMAND = _descriptor.Descriptor(
  name='TemperatureCommand',
  full_name='TemperatureCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='TemperatureCommand.action', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='TemperatureCommand.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=297,
)


_CABLE = _descriptor.Descriptor(
  name='Cable',
  full_name='Cable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel', full_name='Cable.channel', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='Cable.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=299,
  serialized_end=335,
)


_STREAMING = _descriptor.Descriptor(
  name='Streaming',
  full_name='Streaming',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='app', full_name='Streaming.app', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='Streaming.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=337,
  serialized_end=373,
)


_TVOPTIONS = _descriptor.Descriptor(
  name='TVOptions',
  full_name='TVOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Cable', full_name='TVOptions.Cable', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='streaming', full_name='TVOptions.streaming', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=375,
  serialized_end=440,
)


_TVCOMMAND = _descriptor.Descriptor(
  name='TVCommand',
  full_name='TVCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='TVCommand.action', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='TVCommand.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=442,
  serialized_end=484,
)


_TIMEDATA = _descriptor.Descriptor(
  name='TimeData',
  full_name='TimeData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='current_time', full_name='TimeData.current_time', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=486,
  serialized_end=518,
)


_LAMPCOMMAND = _descriptor.Descriptor(
  name='LampCommand',
  full_name='LampCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='LampCommand.action', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lamp_state', full_name='LampCommand.lamp_state', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='upper_limit_lamp', full_name='LampCommand.upper_limit_lamp', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lower_limit_lamp', full_name='LampCommand.lower_limit_lamp', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=520,
  serialized_end=621,
)

_DEVICELIST.fields_by_name['devices'].message_type = _DEVICEINFO
_TVOPTIONS.fields_by_name['Cable'].message_type = _CABLE
_TVOPTIONS.fields_by_name['streaming'].message_type = _STREAMING
DESCRIPTOR.message_types_by_name['ClientCommand'] = _CLIENTCOMMAND
DESCRIPTOR.message_types_by_name['DeviceInfo'] = _DEVICEINFO
DESCRIPTOR.message_types_by_name['DeviceList'] = _DEVICELIST
DESCRIPTOR.message_types_by_name['TemperatureData'] = _TEMPERATUREDATA
DESCRIPTOR.message_types_by_name['TemperatureCommand'] = _TEMPERATURECOMMAND
DESCRIPTOR.message_types_by_name['Cable'] = _CABLE
DESCRIPTOR.message_types_by_name['Streaming'] = _STREAMING
DESCRIPTOR.message_types_by_name['TVOptions'] = _TVOPTIONS
DESCRIPTOR.message_types_by_name['TVCommand'] = _TVCOMMAND
DESCRIPTOR.message_types_by_name['TimeData'] = _TIMEDATA
DESCRIPTOR.message_types_by_name['LampCommand'] = _LAMPCOMMAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClientCommand = _reflection.GeneratedProtocolMessageType('ClientCommand', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTCOMMAND,
  '__module__' : 'devices_pb2'
  # @@protoc_insertion_point(class_scope:ClientCommand)
  })
_sym_db.RegisterMessage(ClientCommand)

DeviceInfo = _reflection.GeneratedProtocolMessageType('DeviceInfo', (_message.Message,), {
  'DESCRIPTOR' : _DEVICEINFO,
  '__module__' : 'devices_pb2'
  # @@protoc_insertion_point(class_scope:DeviceInfo)
  })
_sym_db.RegisterMessage(DeviceInfo)

DeviceList = _reflection.GeneratedProtocolMessageType('DeviceList', (_message.Message,), {
  'DESCRIPTOR' : _DEVICELIST,
  '__module__' : 'devices_pb2'
  # @@protoc_insertion_point(class_scope:DeviceList)
  })
_sym_db.RegisterMessage(DeviceList)

TemperatureData = _reflection.GeneratedProtocolMessageType('TemperatureData', (_message.Message,), {
  'DESCRIPTOR' : _TEMPERATUREDATA,
  '__module__' : 'devices_pb2'
  # @@protoc_insertion_point(class_scope:TemperatureData)
  })
_sym_db.RegisterMessage(TemperatureData)

TemperatureCommand = _reflection.GeneratedProtocolMessageType('TemperatureCommand', (_message.Message,), {
  'DESCRIPTOR' : _TEMPERATURECOMMAND,
  '__module__' : 'devices_pb2'
  # @@protoc_insertion_point(class_scope:TemperatureCommand)
  })
_sym_db.RegisterMessage(TemperatureCommand)

Cable = _reflection.GeneratedProtocolMessageType('Cable', (_message.Message,), {
  'DESCRIPTOR' : _CABLE,
  '__module__' : 'devices_pb2'
  # @@protoc_insertion_point(class_scope:Cable)
  })
_sym_db.RegisterMessage(Cable)

Streaming = _reflection.GeneratedProtocolMessageType('Streaming', (_message.Message,), {
  'DESCRIPTOR' : _STREAMING,
  '__module__' : 'devices_pb2'
  # @@protoc_insertion_point(class_scope:Streaming)
  })
_sym_db.RegisterMessage(Streaming)

TVOptions = _reflection.GeneratedProtocolMessageType('TVOptions', (_message.Message,), {
  'DESCRIPTOR' : _TVOPTIONS,
  '__module__' : 'devices_pb2'
  # @@protoc_insertion_point(class_scope:TVOptions)
  })
_sym_db.RegisterMessage(TVOptions)

TVCommand = _reflection.GeneratedProtocolMessageType('TVCommand', (_message.Message,), {
  'DESCRIPTOR' : _TVCOMMAND,
  '__module__' : 'devices_pb2'
  # @@protoc_insertion_point(class_scope:TVCommand)
  })
_sym_db.RegisterMessage(TVCommand)

TimeData = _reflection.GeneratedProtocolMessageType('TimeData', (_message.Message,), {
  'DESCRIPTOR' : _TIMEDATA,
  '__module__' : 'devices_pb2'
  # @@protoc_insertion_point(class_scope:TimeData)
  })
_sym_db.RegisterMessage(TimeData)

LampCommand = _reflection.GeneratedProtocolMessageType('LampCommand', (_message.Message,), {
  'DESCRIPTOR' : _LAMPCOMMAND,
  '__module__' : 'devices_pb2'
  # @@protoc_insertion_point(class_scope:LampCommand)
  })
_sym_db.RegisterMessage(LampCommand)


# @@protoc_insertion_point(module_scope)
