# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: devices.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='devices.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rdevices.proto\"6\n\rClientCommand\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x15\n\rtarget_device\x18\x02 \x01(\t\"|\n\nDeviceData\x12\x1b\n\x13\x63urrent_measurement\x18\x01 \x01(\x01\x12\x14\n\x0c\x63urrent_time\x18\x02 \x01(\t\x12\x11\n\tdevice_id\x18\x03 \x01(\t\x12\x13\n\x0bupper_limit\x18\x04 \x01(\t\x12\x13\n\x0blower_limit\x18\x05 \x01(\t\"`\n\rDeviceCommand\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x17\n\x0fset_upper_limit\x18\x03 \x01(\t\x12\x17\n\x0fset_lower_limit\x18\x04 \x01(\tb\x06proto3'
)




_CLIENTCOMMAND = _descriptor.Descriptor(
  name='ClientCommand',
  full_name='ClientCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='ClientCommand.action', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='target_device', full_name='ClientCommand.target_device', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=71,
)


_DEVICEDATA = _descriptor.Descriptor(
  name='DeviceData',
  full_name='DeviceData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='current_measurement', full_name='DeviceData.current_measurement', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='current_time', full_name='DeviceData.current_time', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device_id', full_name='DeviceData.device_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='upper_limit', full_name='DeviceData.upper_limit', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lower_limit', full_name='DeviceData.lower_limit', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=197,
)


_DEVICECOMMAND = _descriptor.Descriptor(
  name='DeviceCommand',
  full_name='DeviceCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='DeviceCommand.action', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='DeviceCommand.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_upper_limit', full_name='DeviceCommand.set_upper_limit', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_lower_limit', full_name='DeviceCommand.set_lower_limit', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=199,
  serialized_end=295,
)

DESCRIPTOR.message_types_by_name['ClientCommand'] = _CLIENTCOMMAND
DESCRIPTOR.message_types_by_name['DeviceData'] = _DEVICEDATA
DESCRIPTOR.message_types_by_name['DeviceCommand'] = _DEVICECOMMAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClientCommand = _reflection.GeneratedProtocolMessageType('ClientCommand', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTCOMMAND,
  '__module__' : 'devices_pb2'
  # @@protoc_insertion_point(class_scope:ClientCommand)
  })
_sym_db.RegisterMessage(ClientCommand)

DeviceData = _reflection.GeneratedProtocolMessageType('DeviceData', (_message.Message,), {
  'DESCRIPTOR' : _DEVICEDATA,
  '__module__' : 'devices_pb2'
  # @@protoc_insertion_point(class_scope:DeviceData)
  })
_sym_db.RegisterMessage(DeviceData)

DeviceCommand = _reflection.GeneratedProtocolMessageType('DeviceCommand', (_message.Message,), {
  'DESCRIPTOR' : _DEVICECOMMAND,
  '__module__' : 'devices_pb2'
  # @@protoc_insertion_point(class_scope:DeviceCommand)
  })
_sym_db.RegisterMessage(DeviceCommand)


# @@protoc_insertion_point(module_scope)
